// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789:web:abcdef123456789abcdef',
    messagingSenderId: '123456789',
    projectId: 'focus-flow-timer',
    authDomain: 'focus-flow-timer.firebaseapp.com',
    storageBucket: 'focus-flow-timer.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789:android:abcdef123456789abcdef',
    messagingSenderId: '123456789',
    projectId: 'focus-flow-timer',
    storageBucket: 'focus-flow-timer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789:ios:abcdef123456789abcdef',
    messagingSenderId: '123456789',
    projectId: 'focus-flow-timer',
    storageBucket: 'focus-flow-timer.appspot.com',
    iosBundleId: 'com.example.focusFlowTimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789:ios:abcdef123456789abcdef',
    messagingSenderId: '123456789',
    projectId: 'focus-flow-timer',
    storageBucket: 'focus-flow-timer.appspot.com',
    iosBundleId: 'com.example.focusFlowTimer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
    appId: '1:123456789:web:abcdef123456789abcdef',
    messagingSenderId: '123456789',
    projectId: 'focus-flow-timer',
    authDomain: 'focus-flow-timer.firebaseapp.com',
    storageBucket: 'focus-flow-timer.appspot.com',
    measurementId: 'G-XXXXXXXXXX',
  );
}