// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZtDXPjI8n_vf55-gUUI4xbVcHA19Wy0g',
    appId: '1:917853416260:web:6c43c80288e339039fc511',
    messagingSenderId: '917853416260',
    projectId: 'focus-flow-timer',
    authDomain: 'focus-flow-timer.firebaseapp.com',
    storageBucket: 'focus-flow-timer.firebasestorage.app',
    measurementId: 'G-GJF1KJ8BC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZtDXPjI8n_vf55-gUUI4xbVcHA19Wy0g',
    appId: '1:917853416260:web:6c43c80288e339039fc511',
    messagingSenderId: '917853416260',
    projectId: 'focus-flow-timer',
    storageBucket: 'focus-flow-timer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZtDXPjI8n_vf55-gUUI4xbVcHA19Wy0g',
    appId: '1:917853416260:web:6c43c80288e339039fc511',
    messagingSenderId: '917853416260',
    projectId: 'focus-flow-timer',
    storageBucket: 'focus-flow-timer.firebasestorage.app',
    iosClientId: '123456789-demo.apps.googleusercontent.com',
    iosBundleId: 'com.example.focusFlowTimer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZtDXPjI8n_vf55-gUUI4xbVcHA19Wy0g',
    appId: '1:917853416260:web:6c43c80288e339039fc511',
    messagingSenderId: '917853416260',
    projectId: 'focus-flow-timer',
    storageBucket: 'focus-flow-timer.firebasestorage.app',
    iosClientId: '123456789-demo.apps.googleusercontent.com',
    iosBundleId: 'com.example.focusFlowTimer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZtDXPjI8n_vf55-gUUI4xbVcHA19Wy0g',
    appId: '1:917853416260:web:6c43c80288e339039fc511',
    messagingSenderId: '917853416260',
    projectId: 'focus-flow-timer',
    authDomain: 'focus-flow-timer.firebaseapp.com',
    storageBucket: 'focus-flow-timer.firebasestorage.app',
    measurementId: 'G-GJF1KJ8BC0',
  );
}